version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Harvestmoon19$
      MYSQL_DATABASE: turntable
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Harvestmoon19$
      - DB_NAME=turntable
      - PORT=3001
      - NODE_ENV=production
      - SESSION_SECRET=thehtsllthenslltiekd
      - BCRYPT_SALT_ROUNDS=10
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_ENABLE_SEARCH=true
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge