services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: turntable
      MYSQL_USER: appuser
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_NAME=turntable
      - PORT=3001
      - NODE_ENV=production
      - BCRYPT_SALT_ROUNDS=10
      - CORS_ORIGINS=https://turntablemusic.app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://13.61.124.162:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: /api
        VITE_ENABLE_SEARCH: "true"
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
